version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - "5433:5433"
    env_file:
      - .env
    volumes:
      - deliveryapi_postgres_data:/var/lib/postgresql/data

  deliveryapi:
    image: deliveryapi
    container_name: deliveryapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  deliveryapi_postgres_data: